### ISSUE TITLE
Add New button uses post_type but not the post type singular label

### ISSUE THREAD

**Issue by sc0ttkclark** [createwithrani/add-new-post#1]
The "Add New {post type}" button looks fantastic but it shows the `post_type` value instead of the singular label of that registered post type.

# Expected

> Add New Repeatable Test

_Note: the singular label is "Repeatable Test"_

# Actual

> Add New Repeatable_test

_Note: the `post_type` is "repeatable_test"_

<img width="835" alt="Screen Shot 2022-02-01 at 9 58 20 PM" src="https://user-images.githubusercontent.com/709662/152091022-7fcb0351-f7fb-45d8-b3b9-7ce323b985e1.png">

**Comment by aurooba** [comment]
Thanks for this, @sc0ttkclark! I should totally be pulling in labels instead of the slug. It has been fiiixed!
